# Generated by Django 2.2.13 on 2020-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_comments', models.CharField(max_length=400)),
                ('movies_stars', models.IntegerField()),
                ('movie_comment_date', models.CharField(max_length=20)),
            ],
        ),
    ]
